version: "3"
services:
  nginx:
    image: 192.168.1.5:5000/nginx-php-fpm-python3:${BASE_IMAGE_VERSION}
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${NGINX_SITES_DIR}:/etc/nginx/sites-enabled/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${PHP7_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP7_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
      - ${SUPERVISOR_LOG_DIR}:/var/log/supervisor/:rw
    restart: always
    networks:
      - default

networks:
  default:
