version: "3"
services:
  nginx-php-fpm-python3:
    container_name: nginx-php-fpm-python3
    image: soarfreely/nginx-php-fpm-python3:${BASE_IMAGE_VERSION}
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
      - "${PYTHON_SOCKET_PORT}:8237"
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${NGINX_SITES_DIR}:/etc/nginx/sites-enabled/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${PHP7_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP7_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
      - ${SUPERVISOR_LOG_DIR}:/var/log/supervisor/:rw
#     - ${PYTHON_TOOL_DIR}:/tmp/python/:rw
    restart: always
    networks:
      - default

  mysql:
    container_name: mysql57
    image: mysql:${MYSQL_VERSION}
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  redis:
    container_name: redis
    image: redis:${REDIS_VERSION}
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    networks:
      - default

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "${PHP_MY_ADMIN_HOST_PORT}:80"
    networks:
      - default
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306

  phpredisadmin:
    container_name: phpredisadmin
    image: erikdubbelboer/phpredisadmin:latest
    ports:
      - "${REDIS_MY_ADMIN_HOST_PORT}:80"
    networks:
      - default
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
networks:
  default:
